version: '3.7'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
            - '80:80'
        volumes:
            - '/var/run/docker.sock:/tmp/docker.sock:ro'
        networks:
            - sf3-network

    nginx:
        build: .docker/nginx
        container_name: nginx
        environment:
            VIRTUAL_HOST: mon-site.localhost
        volumes:
            - '.docker/nginx/conf/conf.d:/etc/nginx/conf.d:ro'
            - './:/var/www/'
        links:
            - php-fpm:php
        networks:
            - sf3-network

    php-fpm:
        build: .docker/php-fpm
        container_name: php-fpm
        volumes:
            - './:/var/www/'
        links:
            - blackfire:blackfire
        external_links:
            - mysql-server:mysql-server.localhost
        networks:
            - sf3-network

    blackfire:
        image: blackfire/blackfire
        container_name: blackfire
        environment:
            - BLACKFIRE_LOG_LEVEL=4
            - BLACKFIRE_CLIENT_ID
            - BLACKFIRE_CLIENT_TOKEN
            - BLACKFIRE_SERVER_ID
            - BLACKFIRE_SERVER_TOKEN
        ports:
            - "8707:8707"
        links:
            - nginx-proxy:mon-site.localhost
        networks:
            - sf3-network

    mysql-server:
        image: mysql
        container_name: mysql-server
        volumes:
            - mysql-data:/var/lib/mysql
        links:
            - php-fpm:php-fpm
        networks:
            - sf3-network
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_ROOT_HOST: '%'
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password', '--default_password_lifetime=0']

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            VIRTUAL_HOST: 'pma.localhost'
            PMA_HOST: 'mysql-server.localhost'
            PMA_USER: 'root'
            PMA_PASSWORD: 'root'
        links:
            - mysql-server:mysql-server.localhost
        networks:
            - sf3-network

volumes:
    mysql-data:

networks:
    sf3-network:
